# fly.toml app configuration file generated for bobiverse-tracker on 2026-05-26T17:52:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bobiverse-tracker'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 10
    soft_limit = 5

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/_stcore/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
